/*===========================================================================================
 * name          : p4c.h
 * Author        : Ying He
 * Version       :
 * Copyright     :
 * Description   : Header file for p4c.c
 * 
 * Oct-6-2016 	splitted for p4c.h
 * 		add documentation and comments
 *=========================================================================================== 
 */
#ifndef _P4C_H_
#define _P4C_H_

#include <stdio.h>
#include <stdint.h>

/* 
 * Comsumer buffer size
 * it buffers the data from producer and 
 * triiger aio write when 1/2 full
 *--------------------------------------------
 * limitations:
 * * the min size shall be PROD_BUFF_SIZE * 4
 * * increase the size can improve performance 
 * * This buffer located in .BSS, 
 */
#define CONS_BUFF_SIZE  1024

/* 
 * Producer buffer size
 *--------------------------------------------
 * limitations:
 * * defined in requirement
 */
#define PROD_BUFF_SIZE  64   //64

/* 
 * Data log file size 
 * Consumer thread write this file 
 * with all data generated by Producer
 *--------------------------------------------
 * limitations:
 * * the max values are various in differnet system 
 */
#define LOG_FILE_SIZE   1048574	/*1M*/


/* 
 * Producer sleep timer in us
 * Consumer sleep timer in us 
 * To control the r/w speed and interaction between 
 * producer and Consumer  
 */
#define PRODUCT_SPEED   0  //us
#define CONSUM_SPEED    0  //us
//#define INIT_NUM        0

/* 
 * Producer buffer size
 *--------------------------------------------
 * limitations:
 * * defined in requirement
 */
#define MAX_WRITE       50.0  //50.0

/* 
 * Producer buffer size
 *--------------------------------------------
 * limitations:
 * * defined in requirement
 */
#define MAX_READ        64.0  //64.0

/* 
 * start and end char for random char generator
 * can be changed to '0' and 'z'+1
 * without +1, 'z' will not show up in the file
 *--------------------------------------------
 * limitations:
 * * defined in requirement
 */
#define CHAR_START      'a'
#define CHAR_END        'z'+1

/* 
 * Data log file path and name
 *--------------------------------------------
 * limitations:
 * * debug version and release version have the same file
 * * overwritten after each execution
 */
#define DATALOGFILE	"./datalog_p4c.txt"

/* 
 * BOOL 
 */
#ifndef TRUE
#define TRUE 1
#endif

#ifndef FALSE
#define FALSE 0
#endif


/*
 * Producer buffer data structure, cycle buffer
 * Producer and Consumer: Read and Write
 */
typedef struct producer_buff{
  	/*
	 * location for data head,
	 * producer write after this position
 	 */
  	size_t  begin;
	/*
	 * location of data end
	 * consumer read from this position 
	 */
  	size_t  end;
	/*
	 * number of chars in the pdata buffer
	 */
  	size_t  counter;
	/*
	 * data buffer
	 */
  	uint8_t pdata[PROD_BUFF_SIZE];
}producer_buff_t;

/*
 * Consumer buffer data structure, cycle buffer
 * Consumer thread: Read and Write
 * Producer thread: Read only
 */
typedef struct consumer_buff{
	/*
	 * write data into buffer start from data_p
	 */
  	size_t  data_p;
	/*
	 *write data into file start from aio_p in the buffer
 	 */
  	size_t  aio_p;
	/*
	 * indicator for file full
	 */
  	size_t  filefull;
	/*
	 * available cahr number in the buffer
	 */
  	size_t  counter;
	/*
	 * current data log file length
	 */
  	size_t  file_len;
	/*
	 * Data buffer
	 */
  	uint8_t cdata[CONS_BUFF_SIZE];
}consumer_buff_t;
	  
#endif /*_P4C_H_*/

